MODE:
  RANDOCC: False

SOURCE_DATASET:
  IMG_DIR: "./dataset/CelebAMask-HQ-WO-Train_img/"
  MASK_DIR: "./dataset/CelebAMask-HQ-WO-Train_mask/"

OCCLUDER_DATASET:
  IMG_DIR: "./dataset/11k-hands_img"
  MASK_DIR: "./dataset/11k-hands_mask"

OUTPUT_PATH: "./Result/RandOcc/"

#whether to generate mask of occlusion( for RainNet)
OCCLUSION_MASK: True

AUGMENTATION:
  SOT: True
  ROTATE_AROUND_CENTER: True
